"""empty message

Revision ID: b23aaf5a8d55
Revises: 8b9c7dd61882
Create Date: 2024-02-26 15:31:05.762503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23aaf5a8d55'
down_revision: Union[str, None] = '8b9c7dd61882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('databases', sa.Column('backup_period', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('databases', 'backup_period')
    # ### end Alembic commands ###
