"""empty message

Revision ID: 79ce85f3f520
Revises: b23aaf5a8d55
Create Date: 2024-02-27 09:59:00.248159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ce85f3f520'
down_revision: Union[str, None] = 'b23aaf5a8d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('databases', sa.Column('differential_backup_cron', sa.String(), nullable=False))
    op.add_column('databases', sa.Column('full_backup_cron', sa.String(), nullable=False))
    op.drop_column('databases', 'backup_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('databases', sa.Column('backup_period', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('databases', 'full_backup_cron')
    op.drop_column('databases', 'differential_backup_cron')
    # ### end Alembic commands ###
